name: Build Android APK
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Haskell Stack
        uses: haskell-actions/setup@v2
        with:
          enable-stack: true
          stack-version: 'latest'

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential libgmp-dev zlib1g-dev

      - name: Build android libs
        run: |
          cd apps/multiplatform
          make android

      - name: Build APK
        run: |
          cd apps/multiplatform
          ./gradlew assembleRelease

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: SimplexChat-AutoVideo
          path: apps/multiplatform/android/build/outputs/apk/release/*.apk
